'use client'
import './globals.css'
import type { Metadata } from 'next'
import { useEffect, useState, useRef } from 'react'
import { Inter } from 'next/font/google'
import TopBar from './Components/TopBar'
import Header from './Components/Header'
import Footer from './Components/Footer'
import Language from './Components/Language'
import { data } from 'autoprefixer'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [languagePopupStatus, setlanguagePopupStatus] = useState<boolean>(false)
  const setLang = (data: boolean) => {
    setlanguagePopupStatus(!languagePopupStatus)
  }
  function useOutsideAlerter(ref: any) {
    useEffect(() => {
      /**
       * Alert if clicked on outside of element
       */
      function handleClickOutside(event: any) {
        if (ref.current && !ref.current.contains(event.target)) {
          // setlanguagePopupStatus(false);
          console.log(event.target)
        }
      }
      // Bind the event listener
      document.addEventListener("mousedown", handleClickOutside);
      return () => {
        // Unbind the event listener on clean up
        document.removeEventListener("mousedown", handleClickOutside);
      };
    }, [ref]);
  }
  const wrapperRef = useRef(null);
  useOutsideAlerter(wrapperRef);
  return (
    <html lang="en">
      <body className={`${inter.className} w-full min-h-screen font-Poppins`}>
        <div className='w-full sticky top-0 z-10'>
          <TopBar />
          <Header setLang={setLang} />
          <Language languagePopupStatus={languagePopupStatus} />
        </div>
        <main ref={wrapperRef}>
          {children}
        </main>
        <div className='w-full'>
          <Footer />
        </div>
      </body>
    </html>
  )
}
